version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db/
    ports:
      - 27017-27019:27017-27019

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081